name: Server CI

on:
  push:
    branches: [ main ]
    paths: [ server/** ]
  pull_request:
    branches: [ main ]
    paths: [ server/** ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run tests
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
        working-directory: ./server
        run: |
          npm ci
          npm test 